name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - local_path: 'packages/core'
            split_repository: 'opentelemetry-auto-class'
          - local_path: 'packages/symfony'
            split_repository: 'opentelemetry-auto-class-symfony'
          - local_path: 'packages/laravel'
            split_repository: 'opentelemetry-auto-class-laravel'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
        with:
          package_directory: ${{ matrix.package.local_path }}
          repository_organization: 'eerzho'
          repository_name: ${{ matrix.package.split_repository }}
          tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          user_name: 'eerzho'
          user_email: 'eerzho@gmail.com'
